version: '3.1'
services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: app
    ports: 
      - 9000:80
    volumes: 
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/nginx/conf.d:/etc/nginx/conf.d
      - /root/nginx/dist:/usr/share/nginx/html
      - /root/nginx/logs:/var/log/nginx