version: '3.1'
services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: app
    ports: 
      - 9000:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
  